name: Playit Agent
version: "1.0.3"
slug: playit-agent
description: Run a Playit.gg tunnel agent on Home Assistant
arch:
  - amd64

startup: services
boot: auto
init: false

options:
  secret_key: ""

schema:
  secret_key: password
